version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "rn:aws:ecs:ap-southeast-1:274201610284:task-definition/taskD_process_pension_842201:1"
        LoadBalancerInfo:
          ContainerName: "process_pension_container_842201"
          ContainerPort: 80
        PlatformVersion: "LATEST"